
package com.motek.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TextAnalyzer", targetNamespace = "http://soa.motek.com/")
public interface TextAnalyzer {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.motek.soa.Report
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countSpaces", targetNamespace = "http://soa.motek.com/", className = "com.motek.soa.CountSpaces")
    @ResponseWrapper(localName = "countSpacesResponse", targetNamespace = "http://soa.motek.com/", className = "com.motek.soa.CountSpacesResponse")
    public Report countSpaces(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
