
package com.motek.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TextAnalyzerService", targetNamespace = "http://soa.motek.com/", wsdlLocation = "file:/home/motek/Programming/soa-agh-course/lab9/zad3/textAnalyzer.wsdl")
public class TextAnalyzerService
    extends Service
{

    private final static URL TEXTANALYZERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TEXTANALYZERSERVICE_EXCEPTION;
    private final static QName TEXTANALYZERSERVICE_QNAME = new QName("http://soa.motek.com/", "TextAnalyzerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/motek/Programming/soa-agh-course/lab9/zad3/textAnalyzer.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEXTANALYZERSERVICE_WSDL_LOCATION = url;
        TEXTANALYZERSERVICE_EXCEPTION = e;
    }

    public TextAnalyzerService() {
        super(__getWsdlLocation(), TEXTANALYZERSERVICE_QNAME);
    }

    public TextAnalyzerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEXTANALYZERSERVICE_QNAME, features);
    }

    public TextAnalyzerService(URL wsdlLocation) {
        super(wsdlLocation, TEXTANALYZERSERVICE_QNAME);
    }

    public TextAnalyzerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEXTANALYZERSERVICE_QNAME, features);
    }

    public TextAnalyzerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TextAnalyzerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TextAnalyzer
     */
    @WebEndpoint(name = "TextAnalyzerPort")
    public TextAnalyzer getTextAnalyzerPort() {
        return super.getPort(new QName("http://soa.motek.com/", "TextAnalyzerPort"), TextAnalyzer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TextAnalyzer
     */
    @WebEndpoint(name = "TextAnalyzerPort")
    public TextAnalyzer getTextAnalyzerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.motek.com/", "TextAnalyzerPort"), TextAnalyzer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEXTANALYZERSERVICE_EXCEPTION!= null) {
            throw TEXTANALYZERSERVICE_EXCEPTION;
        }
        return TEXTANALYZERSERVICE_WSDL_LOCATION;
    }

}
