<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://example/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="HelloWorldService" targetNamespace="http://example/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://example/" elementFormDefault="unqualified" targetNamespace="http://example/" version="1.0">

  <xs:element name="sayHelloWorldFrom" type="tns:sayHelloWorldFrom"/>

  <xs:element name="sayHelloWorldFromResponse" type="tns:sayHelloWorldFromResponse"/>

  <xs:complexType name="sayHelloWorldFrom">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sayHelloWorldFromResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="sayHelloWorldFrom">
    <wsdl:part element="tns:sayHelloWorldFrom" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sayHelloWorldFromResponse">
    <wsdl:part element="tns:sayHelloWorldFromResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="HelloWorld">
    <wsdl:operation name="sayHelloWorldFrom">
      <wsdl:input message="tns:sayHelloWorldFrom" name="sayHelloWorldFrom">
    </wsdl:input>
      <wsdl:output message="tns:sayHelloWorldFromResponse" name="sayHelloWorldFromResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HelloWorldServiceSoapBinding" type="tns:HelloWorld">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sayHelloWorldFrom">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="sayHelloWorldFrom">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sayHelloWorldFromResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HelloWorldService">
    <wsdl:port binding="tns:HelloWorldServiceSoapBinding" name="HelloWorldPort">
      <soap:address location="http://localhost:8080/untitled1_war_exploded/HelloWorld"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>