
package com.motek.soa;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HolidaysCountDown", targetNamespace = "http://soa.motek.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HolidaysCountDown {


    /**
     * 
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCount", targetNamespace = "http://soa.motek.com/", className = "com.motek.soa.GetCount")
    @ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://soa.motek.com/", className = "com.motek.soa.GetCountResponse")
    public Long getCount();

}
