
package com.motek.soa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HolidaysCountDownService", targetNamespace = "http://soa.motek.com/", wsdlLocation = "http://localhost:8080/HolidaysService_war_exploded/HolidaysCountDown?wsdl")
public class HolidaysCountDownService
    extends Service
{

    private final static URL HOLIDAYSCOUNTDOWNSERVICE_WSDL_LOCATION;
    private final static WebServiceException HOLIDAYSCOUNTDOWNSERVICE_EXCEPTION;
    private final static QName HOLIDAYSCOUNTDOWNSERVICE_QNAME = new QName("http://soa.motek.com/", "HolidaysCountDownService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/HolidaysService_war_exploded/HolidaysCountDown?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOLIDAYSCOUNTDOWNSERVICE_WSDL_LOCATION = url;
        HOLIDAYSCOUNTDOWNSERVICE_EXCEPTION = e;
    }

    public HolidaysCountDownService() {
        super(__getWsdlLocation(), HOLIDAYSCOUNTDOWNSERVICE_QNAME);
    }

    public HolidaysCountDownService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOLIDAYSCOUNTDOWNSERVICE_QNAME, features);
    }

    public HolidaysCountDownService(URL wsdlLocation) {
        super(wsdlLocation, HOLIDAYSCOUNTDOWNSERVICE_QNAME);
    }

    public HolidaysCountDownService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOLIDAYSCOUNTDOWNSERVICE_QNAME, features);
    }

    public HolidaysCountDownService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HolidaysCountDownService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HolidaysCountDown
     */
    @WebEndpoint(name = "HolidaysCountDownPort")
    public HolidaysCountDown getHolidaysCountDownPort() {
        return super.getPort(new QName("http://soa.motek.com/", "HolidaysCountDownPort"), HolidaysCountDown.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolidaysCountDown
     */
    @WebEndpoint(name = "HolidaysCountDownPort")
    public HolidaysCountDown getHolidaysCountDownPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soa.motek.com/", "HolidaysCountDownPort"), HolidaysCountDown.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOLIDAYSCOUNTDOWNSERVICE_EXCEPTION!= null) {
            throw HOLIDAYSCOUNTDOWNSERVICE_EXCEPTION;
        }
        return HOLIDAYSCOUNTDOWNSERVICE_WSDL_LOCATION;
    }

}
