
package com.motek.soa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Kantor", targetNamespace = "http://soa.motek.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Kantor {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     * @throws UnsupportedCurrencyException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "zamien", targetNamespace = "http://soa.motek.com/", className = "com.motek.soa.Zamien")
    @ResponseWrapper(localName = "zamienResponse", targetNamespace = "http://soa.motek.com/", className = "com.motek.soa.ZamienResponse")
    public Double zamien(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Double arg1)
        throws UnsupportedCurrencyException_Exception
    ;

}
