
package com.motek.soa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UnsupportedCurrencyException", targetNamespace = "http://soa.motek.com/")
public class UnsupportedCurrencyException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnsupportedCurrencyException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UnsupportedCurrencyException_Exception(String message, UnsupportedCurrencyException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UnsupportedCurrencyException_Exception(String message, UnsupportedCurrencyException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.motek.soa.UnsupportedCurrencyException
     */
    public UnsupportedCurrencyException getFaultInfo() {
        return faultInfo;
    }

}
